##########################  for pin,body,base ##########################
# slice(offset, offset)
# offset = Y + height
DEFAULT_ROI_Y = 400
DEFAULT_ROI_HEIGHT = 250
DEFAULT_ROT_HEIGHT_OFFSET = DEFAULT_ROI_Y + DEFAULT_ROI_HEIGHT

DEFAULT_HEIGHT = slice(DEFAULT_ROI_Y, DEFAULT_ROT_HEIGHT_OFFSET)

# Pin tip 
# offset = X + width
PIN_TIP_X = 410 
PIN_TIP_WIDTH = 150

PIN_TIP_WIDTH_OFFSET = PIN_TIP_X + PIN_TIP_WIDTH

PIN_TIP = slice(PIN_TIP_X, PIN_TIP_WIDTH_OFFSET)

# Pin body 
PIN_BODY_X = 500
PIN_BODY_WIDTH = 161

PIN_BODY_WIDTH_OFFSET = PIN_BODY_X + PIN_BODY_WIDTH

PIN_BODY = slice(PIN_BODY_X, PIN_BODY_WIDTH_OFFSET)

# Pin base 
PIN_BASE_X = 640
PIN_BASE_WIDTH = 50

PIN_BASE_WIDTH_OFFSET = PIN_BASE_X + PIN_BASE_WIDTH

PIN_BASE = slice(PIN_BASE_X, PIN_BASE_WIDTH_OFFSET)

########################## Tilt check  parameters ##########################
# Setting the width = -10 the width of the image
TILT_CHECK_X = 0
TILT_CHECK_WIDTH = PIN_BASE_WIDTH - 10
TILT_CHECK_WIDTH_OFFSET = TILT_CHECK_X + TILT_CHECK_WIDTH

TILT_CHECK_ROI_WIDTH = slice(TILT_CHECK_X, TILT_CHECK_WIDTH_OFFSET)

# Setting the hights
TILT_CHECK_HEIGHT = 75

# Top crop
TILT_CHECK_TOP_Y = 175
TILT_CHECK_TOP_HEIGHT_OFFSET = TILT_CHECK_HEIGHT + TILT_CHECK_TOP_Y
TILT_CHECK_TOP = slice(TILT_CHECK_TOP_Y, TILT_CHECK_TOP_HEIGHT_OFFSET)

# Bottom crop
TILT_CHECK_BOTTOM_Y = 282
TILT_CHECK_BOTTOM_HEIGHT_OFFSET = TILT_CHECK_HEIGHT - TILT_CHECK_BOTTOM_Y
TILT_CHECK_BOTTOM = slice(TILT_CHECK_BOTTOM_Y, TILT_CHECK_BOTTOM_HEIGHT_OFFSET)

########################## Pin check parameters ##########################
# No width is needed here
PIN_CHECK_HEIGHT = 100
# Top crop
PIN_CHECK_TOP_Y = 140
PIN_CHECK_TOP_HEIGHT_OFFSET = PIN_CHECK_HEIGHT + PIN_CHECK_TOP_Y
PIN_CHECK_TOP = slice(PIN_CHECK_TOP_Y, PIN_CHECK_TOP_HEIGHT_OFFSET)

# Bottom crop
PIN_CHECK_BOTTOM_Y = 285
PIN_CHECK_BOTTOM_HEIGHT_OFFSET = PIN_CHECK_HEIGHT + PIN_CHECK_BOTTOM_Y
PIN_CHECK_BOTTOM = slice(PIN_CHECK_BOTTOM_Y, PIN_CHECK_BOTTOM_HEIGHT_OFFSET)

########################## X,Y,Z check parameters ##########################
MIN_X = -2
MAX_X = 2

MIN_Y = -2
MAX_Y = 2

MIN_Z = -2
MAX_Z = 2

# # Y motor axis is up if = 1
# # Y motor axis is down if = 0
# PIN_ALIGN_Y_UP = 1

# # Z motor axis is up if = 1
# # Z motor axis is down if = 0
# PIN_ALIGN_Z_UP = 0

# PIN_ALIGN_DEFAULT_ROI_WIDTH = 150
# PIN_ALIGN_DEFAULT_ROI_WIDTH_OFFSET = 410
# PIN_ALIGN_DEFAULT_PIXELS_PER_MM = 26
# PIN_ALIGN_DEFAULT_IMAGE_WIDTH_CENTER = 470
# PIN_ALIGN_DEFAULT_IMAGE_HEIGHT_CENTER = 453